//---------------------------------------------------------------------------------
// The MIT License (MIT)
//
// Copyright (c) 2015-2018 Sergej Zuyev (sergej.zuyev - at - zz-systems.net)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//---------------------------------------------------------------------------------

/**
 * @file int16.impl.hpp
 * @brief
 * This file provides defines required components and logic for int16 sse target.
 * Provides unified access to 8 'int16_t' values
 * @remark
 * This is an autogenerated file. Changes will be lost on regeneration.
 */
#pragma once

#include <type_traits>
#include <cmath>

#include "backend/intrin.hpp"
#include "backend/zval.hpp"

#include "util/type/type_composition.hpp"
#include "util/type/type_traits.hpp"

#include "util/memory.hpp"
#include "util/macros.hpp"

#include "traits/convertable.hpp"
#include "traits/printable.hpp"
#include "traits/bitwise.hpp"
#include "traits/io.hpp"
#include "traits/bitwise_shift.hpp"
#include "traits/math.hpp"
#include "traits/conditional.hpp"
#include "traits/logical.hpp"
#include "traits/numeric.hpp"
#include "traits/comparable.hpp"
#include "traits/arithmetic.hpp"
#include "traits/equatable.hpp"

namespace zacc { namespace backend { namespace sse
{
    /// @cond
    template<uint64_t features>
    struct bint16;

    template<uint64_t features>
    struct zint16;
    /// @endcond

    namespace int16_detail
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m128i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = int16_t;

        /// mask type for boolean operations
        using mask_vector_t = __m128i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /**
         * @brief zval parametrization using
         * - '__m128i' as underlying vector type
         * - 'int16_t' as scalar type
         * - '8' as vector size
         * - '16' as alignment
         * @relates int16
         * @remark sse
         */
        template<uint64_t Features>
        using zval_base = zval<__m128i, __m128i, int16_t, zval_tag, 8, 16, Features>;

        /**
         * @brief bval parametrization using
         * - '__m128i' as underlying vector type
         * - 'int16_t' as scalar type
         * - '8' as vector size
         * - '16' as alignment
         * @relates int16
         * @remark sse
        */
        template<uint64_t Features>
        using bval_base = bval<__m128i, __m128i, int16_t, 8, 16, Features>;
    }
}}}

namespace zacc {

    template<typename T>
    struct ztraits<T, std::enable_if_t<
            std::is_base_of<backend::sse::int16_detail::zval_base<T::feature_mask>, T>::value
            || std::is_base_of<backend::sse::int16_detail::bval_base<T::feature_mask>, T>::value>>
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// capabilities
        static constexpr uint64_t feature_mask = T::feature_mask;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m128i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = int16_t;

        /// mask type for boolean operations
        using mask_vector_t = __m128i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        using zval_t = backend::sse::zint16<T::feature_mask>;
        using bval_t = backend::sse::bint16<T::feature_mask>;

        using tag = select_t<
                when<std::is_base_of<backend::sse::int16_detail::zval_base<T::feature_mask>, T>::value, zval_tag>,
                when<std::is_base_of<backend::sse::int16_detail::bval_base<T::feature_mask>, T>::value, bval_tag>>;
    };
}

namespace zacc { namespace backend { namespace sse {

    namespace int16_detail {

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_io
        {
            /**
             * @brief io basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vstore");

                    _mm_store_si128((__m128i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vstream");

                    _mm_stream_si128((__m128i*)&(*result), input);
                }

            };

            /**
             * @brief io public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name math modules
         */
        ///@{
        /**
         * @brief math
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_math
        {
            /**
             * @brief math basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief math sse4
                 * @relates int16
                 * @remark sse sse4
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE3>, T> vabs(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "sse4", "vabs");

                    return _mm_abs_epi16(one);
                }


                /**
                 * @brief math default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE3>, T> vabs(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vabs");

                    return vmax(one, -one);
                }


                /**
                 * @brief math sse4
                 * @relates int16
                 * @remark sse sse4
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> vmin(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "sse4", "vmin");

                    return _mm_min_epi16(one, other);
                }


                /**
                 * @brief math default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> vmin(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vmin");

                    return vsel(one < other, one, other);
                }


                /**
                 * @brief math sse4
                 * @relates int16
                 * @remark sse sse4
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> vmax(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "sse4", "vmax");

                    return _mm_max_epi16(one, other);
                }


                /**
                 * @brief math default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> vmax(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vmax");

                    return vsel(one > other, one, other);
                }


                /**
                 * @brief math default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vclamp(Composed self, Composed from, Composed to) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vclamp");

                    return vmin(to, vmax(from, self));
                }

            };

            /**
             * @brief math public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::math<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name numeric modules
         */
        ///@{
        /**
         * @brief numeric
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_numeric
        {
            /**
             * @brief numeric basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {
            };

            /**
             * @brief numeric public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::numeric<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name arithmetic modules
         */
        ///@{
        /**
         * @brief arithmetic
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_arithmetic
        {
            /**
             * @brief arithmetic basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief arithmetic default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vneg");

                    return _mm_sub_epi16(_mm_setzero_si128(), one);
                }


                /**
                 * @brief arithmetic default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vadd(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vadd");

                    return _mm_add_epi16(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vsub(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vsub");

                    return _mm_sub_epi16(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vmul(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vmul");

                    return _mm_mullo_epi16(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vdiv(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vdiv");

                    auto dividend = one.data();
                    auto divisor = other.data();
                    typename Composed::extracted_t result;
                    for (size_t i = 0; i < Composed::size; i++) { result[i] = dividend[i] / divisor[i]; };
                    return result;
                }


                /**
                 * @brief arithmetic default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vmod(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vmod");

                    return vsub(one, vmul(other, vdiv(one, other)));
                }

            };

            /**
             * @brief arithmetic public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::arithmetic<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbneg");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi16(zero, zero);
                    return _mm_xor_si128(one, ones);
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vband");

                    return _mm_and_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbxor");

                    return _mm_xor_si128(one, other);
                }


                /**
                 * @brief bitwise sse4
                 * @relates int16
                 * @remark sse sse4
                 */
                template<typename T = bool> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "sse4", "is_set");

                    return _mm_test_all_ones(one) != 0;
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename T = bool> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "is_set");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi32(zero, zero);
                    return _mm_movemask_epi8(_mm_cmpeq_epi16(one, ones)) == 0xFFFF;
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise_shift modules
         */
        ///@{
        /**
         * @brief bitwise_shift
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_bitwise_shift
        {
            /**
             * @brief bitwise_shift basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief bitwise_shift default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vbsll(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbsll");

                    return _mm_sll_epi16(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vbsrl(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbsrl");

                    return _mm_srl_epi16(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vbslli(const Composed one, const size_t other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbslli");

                    return _mm_slli_epi16(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int16
                 * @remark sse default
                 */
                friend zint16<Interface::feature_mask> vbsrli(const Composed one, const size_t other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbsrli");

                    return _mm_srli_epi16(one, other);
                }

            };

            /**
             * @brief bitwise_shift public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::bitwise_shift<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name comparable modules
         */
        ///@{
        /**
         * @brief comparable
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_comparable
        {
            /**
             * @brief comparable basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief comparable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vgt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vgt");

                    return _mm_cmpgt_epi16(one, other);
                }


                /**
                 * @brief comparable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vlt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vlt");

                    return _mm_cmplt_epi16(one, other);
                }


                /**
                 * @brief comparable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vge(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vge");

                    return !(one < other);
                }


                /**
                 * @brief comparable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vle(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vle");

                    return !(one > other);
                }

            };

            /**
             * @brief comparable public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::comparable<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vlneg");

                    return _mm_cmpeq_epi16(one, _mm_setzero_si128());
                }


                /**
                 * @brief logical default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vlor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief logical default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vland");

                    return _mm_and_si128(one, other);
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "veq");

                    return _mm_cmpeq_epi16(one, other);
                }


                /**
                 * @brief equatable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vneq");

                    return !(one == other);
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name conditional modules
         */
        ///@{
        /**
         * @brief conditional
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint16_conditional
        {
            /**
             * @brief conditional basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief conditional sse4
                 * @relates int16
                 * @remark sse sse4
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> vsel(bint16<Interface::feature_mask> condition, Composed if_value, Composed else_value) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "sse4", "vsel");

                    return _mm_blendv_epi8(else_value, if_value, condition);
                }


                /**
                 * @brief conditional default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename T = zint16<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> vsel(bint16<Interface::feature_mask> condition, Composed if_value, Composed else_value) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vsel");

                    return _mm_or_si128(_mm_andnot_si128(condition, else_value), _mm_and_si128(condition, if_value));
                }

            };

            /**
             * @brief conditional public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::conditional<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint16_io
        {
            /**
             * @brief io basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vstore");

                    _mm_store_si128((__m128i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vstream");

                    _mm_stream_si128((__m128i*)&(*result), input);
                }

            };

            /**
             * @brief io public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint16_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbneg");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi16(zero, zero);
                    return _mm_xor_si128(one, ones);
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vband");

                    return _mm_and_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vbxor");

                    return _mm_xor_si128(one, other);
                }


                /**
                 * @brief bitwise sse4
                 * @relates int16
                 * @remark sse sse4
                 */
                template<typename T = bool> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "sse4", "is_set");

                    return _mm_test_all_ones(one) != 0;
                }


                /**
                 * @brief bitwise default
                 * @relates int16
                 * @remark sse default
                 */
                template<typename T = bool> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "is_set");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi32(zero, zero);
                    return _mm_movemask_epi8(_mm_cmpeq_epi16(one, ones)) == 0xFFFF;
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint16_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vlneg");

                    return _mm_cmpeq_epi16(one, _mm_setzero_si128());
                }


                /**
                 * @brief logical default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vlor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief logical default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vland");

                    return _mm_and_si128(one, other);
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates int16
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint16_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates int16
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "veq");

                    return _mm_cmpeq_epi16(one, other);
                }


                /**
                 * @brief equatable default
                 * @relates int16
                 * @remark sse default
                 */
                friend bint16<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "default", "vneq");

                    return !(one == other);
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates int16
             * @remark sse
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bint16<Interface::feature_mask>>;
        };

        ///@}


        // Type composition ================================================================================================

        /**
         * @name int16 composition
         */
        ///@{

        /**
         * @brief zval composition
         * @relates int16
         * @remark sse
         * @tparam features feature mask
         */
        template<uint64_t FeatureMask>
        using __zint16 = compose_t
        <
            printable<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            convertable<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_io<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_math<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_numeric<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_arithmetic<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_bitwise<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_bitwise_shift<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_comparable<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_logical<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_equatable<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl,
            zint16_conditional<zval_base<FeatureMask>, zint16<FeatureMask>>::template impl
        >;

        /// bint16 composition
        /// @tparam features feature mask
        template<uint64_t FeatureMask>
        using __bint16 = compose_t
        <
            printable<bval_base<FeatureMask>, bint16<FeatureMask>>::template impl,
            convertable<bval_base<FeatureMask>, bint16<FeatureMask>>::template impl,
            bint16_io<bval_base<FeatureMask>, bint16<FeatureMask>>::template impl,
            bint16_bitwise<bval_base<FeatureMask>, bint16<FeatureMask>>::template impl,
            bint16_logical<bval_base<FeatureMask>, bint16<FeatureMask>>::template impl,
            bint16_equatable<bval_base<FeatureMask>, bint16<FeatureMask>>::template impl
        >;

        ///@}
    } // end namespace

    /// public zint16 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct zint16 :
            public int16_detail::__zint16<FeatureMask>,
            public int16_detail::zval_base<FeatureMask>
    {
        /// type tag
        using tag = zval_tag;

        /// complete vector
        using zval_t = zint16<FeatureMask>;

        /// complete boolean vector
        using bval_t = bint16<FeatureMask>;

        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m128i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = int16_t;

        /// mask type for boolean operations
        using mask_vector_t = __m128i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /**
         * copy constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<std::is_convertible<T, __m128i>::value>>// || std::is_convertible<T, int16_t>::value>>
        constexpr zint16(const T& other) noexcept
                : int16_detail::zval_base<FeatureMask>(other)
        {}

        /**
         * move constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<(size > 1) && std::is_convertible<T, __m128i>::value>>
        constexpr zint16(T&& other) noexcept
            : int16_detail::zval_base<FeatureMask>(std::forward<T>(other))
        {}

        /**
         * copy constructor
         * @param other
         */
        constexpr zint16(const bint16<FeatureMask>& other) noexcept
            : int16_detail::zval_base<FeatureMask>(other.value())
        {}


        /**
         * @brief constructable 
         * @relates int16
         * @remark sse 
         */
        constexpr zint16(  ) noexcept : int16_detail::zval_base<FeatureMask>()
        {
            ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "", "CONS()");

        }


        /**
         * @brief constructable 
         * @relates int16
         * @remark sse 
         */
        constexpr zint16(__m128i value) noexcept : int16_detail::zval_base<FeatureMask>(value)
        {
            ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "", "CONS(__m128i)");

        }


        /**
         * @brief constructable 
         * @relates int16
         * @remark sse 
         */
        constexpr zint16(short value) noexcept : int16_detail::zval_base<FeatureMask>(_mm_set1_epi16(value))
        {
            ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "", "CONS(short)");

        }


        /**
         * @brief constructable 
         * @relates int16
         * @remark sse 
         */
        constexpr zint16(const extracted_t &value) noexcept : int16_detail::zval_base<FeatureMask>(_mm_load_si128((__m128i *) value.data()))
        {
            ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "", "CONS(const extracted_t)");

        }


        /**
         * @brief constructable 
         * @relates int16
         * @remark sse 
         */
        constexpr zint16(int16_t _7, int16_t _6, int16_t _5, int16_t _4, int16_t _3, int16_t _2, int16_t _1, int16_t _0) noexcept : int16_detail::zval_base<FeatureMask>(_mm_set_epi16(_0, _1, _2, _3, _4, _5, _6, _7))
        {
            ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "", "CONS(int16_t, int16_t, int16_t, int16_t, int16_t, int16_t, int16_t, int16_t)");

        }

    };

    /// public bint16 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct bint16 :
            public int16_detail::__bint16<FeatureMask>,
            public int16_detail::bval_base<FeatureMask>
    {
        /// type tag
        using tag = bval_tag;

        /// complete vector
        using zval_t = zint16<FeatureMask>;

        /// complete boolean vector
        using bval_t = bint16<FeatureMask>;

        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m128i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = bool;

        /// mask type for boolean operations
        using mask_vector_t = __m128i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /// Forwarding constructor
        FORWARD2(bint16, int16_detail::bval_base<FeatureMask>);


        /**
         * @brief constructable 
         * @relates int16
         * @remark sse 
         */
        constexpr bint16(  ) noexcept : int16_detail::bval_base<FeatureMask>()
        {
            ZTRACE_BACKEND("sse.int16.impl", __LINE__, "int16(int16_t[8])", "", "CONS()");

        }

    };

    static_assert(is_zval<zint16<0>>::value, "is_zval for zint16 failed.");
    static_assert(is_bval<bint16<0>>::value, "is_bval for bint16 failed.");

    static_assert(!is_floating_point<zint16<0>>::value, "is_floating_point for zint16 failed.");
    static_assert(is_integral<zint16<0>>::value, "is_integral for zint16 failed.");

    static_assert(!is_float<zint16<0>>::value, "is_float for zint16 failed.");
    static_assert(!is_double<zint16<0>>::value, "is_double for zint16 failed.");

    ///@}
}}}