//---------------------------------------------------------------------------------
// The MIT License (MIT)
//
// Copyright (c) 2015-2018 Sergej Zuyev (sergej.zuyev - at - zz-systems.net)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//---------------------------------------------------------------------------------

/**
 * @file int32.impl.hpp
 * @brief
 * This file provides defines required components and logic for int32 sse target.
 * Provides unified access to 4 'int32_t' values
 * @remark
 * This is an autogenerated file. Changes will be lost on regeneration.
 */
#pragma once

#include <type_traits>
#include <cmath>

#include "backend/intrin.hpp"
#include "backend/zval.hpp"
#include "backend/zval_interface.hpp"

#include "util/type/type_composition.hpp"
#include "util/type/type_traits.hpp"

#include "util/memory.hpp"
#include "util/macros.hpp"

#include "traits/convertable.hpp"
#include "traits/printable.hpp"
#include "traits/equatable.hpp"
#include "traits/conditional.hpp"
#include "traits/bitwise_shift.hpp"
#include "traits/comparable.hpp"
#include "traits/logical.hpp"
#include "traits/numeric.hpp"
#include "traits/io.hpp"
#include "traits/bitwise.hpp"
#include "traits/math.hpp"
#include "traits/arithmetic.hpp"

namespace zacc { namespace backend { namespace sse
{
    /// @cond
    template<uint64_t features>
    struct bint32;

    template<uint64_t features>
    struct zint32;
    /// @endcond

    template<uint64_t FeatureMask>
    using izint32 = ztype<zval_tag, __m128i, __m128i, int32_t, 4, 16, FeatureMask>;

    template<uint64_t FeatureMask>
    using ibint32 = ztype<bval_tag, __m128i, __m128i, int32_t, 4, 16, FeatureMask>;

    namespace int32_detail
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 4;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_type = __m128i;

        /// scalar type, like int for sse 4x integer vector
        using element_type = int32_t;

        /// mask type for boolean operations
        using mask_vector_type = __m128i;

        /// extracted std::array of (dim) scalar values
        using extracted_type = std::array<element_type, size>;
    }
}}}

namespace zacc {

    template<typename T>
    struct ztraits<T, std::enable_if_t<
            std::is_base_of<backend::sse::izint32<T::feature_mask>, T>::value
            || std::is_base_of<backend::sse::ibint32<T::feature_mask>, T>::value>>
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 4;

        /// capabilities
        static constexpr uint64_t feature_mask = T::feature_mask;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_type = __m128i;

        /// scalar type, like int for sse 4x integer vector
        using element_type = int32_t;

        /// mask type for boolean operations
        using mask_vector_type = __m128i;

        /// extracted std::array of (dim) scalar values
        using extracted_type = std::array<element_type, size>;

        using zval_t = backend::sse::zint32<T::feature_mask>;
        using bval_t = backend::sse::bint32<T::feature_mask>;

        using tag = select_t<
            when<std::is_base_of<backend::sse::izint32<T::feature_mask>, T>::value, zval_tag>,
            when<std::is_base_of<backend::sse::ibint32<T::feature_mask>, T>::value, bval_tag>>;
    };
}

namespace zacc { namespace backend { namespace sse {

    namespace detail {

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_io
        {
            /**
             * @brief io basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vstore");

                    _mm_store_si128((__m128i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vstream");

                    _mm_stream_si128((__m128i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename RandomIt> friend zint32<Interface::feature_mask> vgather(RandomIt input, const zint32<Interface::feature_mask> &index, Composed) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vgather");

                    auto i = index.data();
                    return _mm_set_epi32(input[i[3]], input[i[2]], input[i[1]], input[i[0]]);
                }

            };

            /**
             * @brief io public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name math modules
         */
        ///@{
        /**
         * @brief math
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_math
        {
            /**
             * @brief math basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief math sse3
                 * @relates int32
                 * @remark sse sse3
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE3>, T> vabs(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "sse3", "vabs");

                    return _mm_abs_epi32(one);
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE3>, T> vabs(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vabs");

                    return vmax(one, -one);
                }


                /**
                 * @brief math sse4
                 * @relates int32
                 * @remark sse sse4
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> vmin(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "sse4", "vmin");

                    return _mm_min_epi32(one, other);
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> vmin(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vmin");

                    return vsel(one < other, one, other);
                }


                /**
                 * @brief math sse4
                 * @relates int32
                 * @remark sse sse4
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> vmax(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "sse4", "vmax");

                    return _mm_max_epi32(one, other);
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> vmax(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vmax");

                    return vsel(one > other, one, other);
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vclamp(Composed self, Composed from, Composed to) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vclamp");

                    return vmin(to, vmax(from, self));
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vsqrt(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vsqrt");

                    return _mm_sqrt_ps(_mm_cvtepi32_ps(one));
                }

            };

            /**
             * @brief math public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::math<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name numeric modules
         */
        ///@{
        /**
         * @brief numeric
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_numeric
        {
            /**
             * @brief numeric basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {
            };

            /**
             * @brief numeric public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::numeric<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name arithmetic modules
         */
        ///@{
        /**
         * @brief arithmetic
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_arithmetic
        {
            /**
             * @brief arithmetic basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vneg");

                    return _mm_sub_epi32(_mm_setzero_si128(), one);
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vadd(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vadd");

                    return _mm_add_epi32(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vsub(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vsub");

                    return _mm_sub_epi32(one, other);
                }


                /**
                 * @brief arithmetic sse4
                 * @relates int32
                 * @remark sse sse4
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> vmul(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "sse4", "vmul");

                    return _mm_mullo_epi32(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> vmul(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vmul");

                    __m128i tmp1 = _mm_mul_epu32(one,other); /* mul 2,0*/;
                    __m128i tmp2 = _mm_mul_epu32( _mm_srli_si128(one,4), _mm_srli_si128(other,4)); /* mul 3,1 */;
                    return _mm_unpacklo_epi32(_mm_shuffle_epi32(tmp1, _MM_SHUFFLE (0,0,2,0)), _mm_shuffle_epi32(tmp2, _MM_SHUFFLE (0,0,2,0)));
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vdiv(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vdiv");

                    return _mm_div_ps(_mm_cvtepi32_ps(one), _mm_cvtepi32_ps(other));
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vmod(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vmod");

                    return vsub(one, vmul(other, vdiv(one, other)));
                }

            };

            /**
             * @brief arithmetic public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::arithmetic<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbneg");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi32(zero, zero);
                    return _mm_xor_si128(one, ones);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vband");

                    return _mm_and_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbxor");

                    return _mm_xor_si128(one, other);
                }


                /**
                 * @brief bitwise sse4
                 * @relates int32
                 * @remark sse sse4
                 */
                template<typename T = bool> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "sse4", "is_set");

                    return _mm_test_all_ones(one) != 0;
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename T = bool> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "is_set");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi32(zero, zero);
                    return _mm_movemask_epi8(_mm_cmpeq_epi32(one, ones)) == 0xFFFF;
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise_shift modules
         */
        ///@{
        /**
         * @brief bitwise_shift
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_bitwise_shift
        {
            /**
             * @brief bitwise_shift basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vbsll(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbsll");

                    return _mm_sll_epi32(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vbsrl(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbsrl");

                    return _mm_srl_epi32(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vbslli(const Composed one, const size_t other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbslli");

                    return _mm_slli_epi32(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark sse default
                 */
                friend zint32<Interface::feature_mask> vbsrli(const Composed one, const size_t other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbsrli");

                    return _mm_srli_epi32(one, other);
                }

            };

            /**
             * @brief bitwise_shift public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::bitwise_shift<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name comparable modules
         */
        ///@{
        /**
         * @brief comparable
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_comparable
        {
            /**
             * @brief comparable basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vgt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vgt");

                    return _mm_cmpgt_epi32(one, other);
                }


                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vlt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vlt");

                    return _mm_cmplt_epi32(one, other);
                }


                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vge(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vge");

                    return !(one < other);
                }


                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vle(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vle");

                    return !(one > other);
                }

            };

            /**
             * @brief comparable public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::comparable<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vlneg");

                    return _mm_cmpeq_epi32(one, _mm_setzero_si128());
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vlor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vland");

                    return _mm_and_si128(one, other);
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "veq");

                    return _mm_cmpeq_epi32(one, other);
                }


                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vneq");

                    return !(one == other);
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name conditional modules
         */
        ///@{
        /**
         * @brief conditional
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct zint32_conditional
        {
            /**
             * @brief conditional basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief conditional sse4
                 * @relates int32
                 * @remark sse sse4
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> vsel(bint32<Interface::feature_mask> condition, Composed if_value, Composed else_value) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "sse4", "vsel");

                    return _mm_blendv_epi8(else_value, if_value, condition);
                }


                /**
                 * @brief conditional default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename T = zint32<Interface::feature_mask>> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> vsel(bint32<Interface::feature_mask> condition, Composed if_value, Composed else_value) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vsel");

                    return _mm_or_si128(_mm_andnot_si128(condition, else_value), _mm_and_si128(condition, if_value));
                }

            };

            /**
             * @brief conditional public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::conditional<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint32_io
        {
            /**
             * @brief io basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vstore");

                    _mm_store_si128((__m128i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vstream");

                    _mm_stream_si128((__m128i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename RandomIt> friend bint32<Interface::feature_mask> vgather(RandomIt input, const zint32<Interface::feature_mask> &index, Composed) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vgather");

                    auto i = index.data();
                    return _mm_set_epi32(input[i[3]], input[i[2]], input[i[1]], input[i[0]]);
                }

            };

            /**
             * @brief io public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint32_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbneg");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi32(zero, zero);
                    return _mm_xor_si128(one, ones);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vband");

                    return _mm_and_si128(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vbxor");

                    return _mm_xor_si128(one, other);
                }


                /**
                 * @brief bitwise sse4
                 * @relates int32
                 * @remark sse sse4
                 */
                template<typename T = bool> friend std::enable_if_t<has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "sse4", "is_set");

                    return _mm_test_all_ones(one) != 0;
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark sse default
                 */
                template<typename T = bool> friend std::enable_if_t<!has_feature_v<Interface, capabilities::SSE41>, T> is_set(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "is_set");

                    auto zero = _mm_setzero_si128();
                    auto ones = _mm_cmpeq_epi32(zero, zero);
                    return _mm_movemask_epi8(_mm_cmpeq_epi32(one, ones)) == 0xFFFF;
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint32_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vlneg");

                    return _mm_cmpeq_epi32(one, _mm_setzero_si128());
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vlor");

                    return _mm_or_si128(one, other);
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vland");

                    return _mm_and_si128(one, other);
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates int32
         * @remark sse
         */
        template<typename Interface, typename Composed>
        struct bint32_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates int32
             * @remark sse
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "veq");

                    return _mm_cmpeq_epi32(one, other);
                }


                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark sse default
                 */
                friend bint32<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "default", "vneq");

                    return !(one == other);
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates int32
             * @remark sse
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}


        // Type composition ================================================================================================

        /**
         * @name int32 composition
         */
        ///@{

        /**
         * @brief zval composition
         * @relates int32
         * @remark sse
         * @tparam features feature mask
         */
        template<uint64_t FeatureMask>
        using zint32_ops = compose_t
        <
            printable<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            convertable<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_io<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_math<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_numeric<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_arithmetic<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_bitwise<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_bitwise_shift<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_comparable<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_logical<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_equatable<izint32<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_conditional<izint32<FeatureMask>, zint32<FeatureMask>>::template impl
        >;

        /// bint32 composition
        /// @tparam features feature mask
        template<uint64_t FeatureMask>
        using bint32_ops = compose_t
        <
            printable<ibint32<FeatureMask>, bint32<FeatureMask>>::template impl,
            convertable<ibint32<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_io<ibint32<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_bitwise<ibint32<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_logical<ibint32<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_equatable<ibint32<FeatureMask>, bint32<FeatureMask>>::template impl
        >;

        ///@}
    } // end namespace

    /// public zint32 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct zint32 :
        public detail::zint32_ops<FeatureMask>,
        public zval<izint32<FeatureMask>>
    {
        USING_ZTYPE(izint32<FeatureMask>);

        /// complete vector
        using zval_t = zint32<FeatureMask>;

        /// complete boolean vector
        using bval_t = bint32<FeatureMask>;

        /**
         * copy constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<std::is_convertible<T, __m128i>::value>>// || std::is_convertible<T, int32_t>::value>>
        constexpr zint32(const T& other) noexcept
            : zval<izint32<FeatureMask>>(other)
        {}

        /**
         * move constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<(size > 1) && std::is_convertible<T, __m128i>::value>>
        constexpr zint32(T&& other) noexcept
            : zval<izint32<FeatureMask>>(std::forward<T>(other))
        {}

        /**
         * copy constructor
         * @param other
         */
        constexpr zint32(const bint32<FeatureMask>& other) noexcept
            : zval<izint32<FeatureMask>>(other.value())
        {}


        /**
         * @brief constructable 
         * @relates int32
         * @remark sse 
         */
        constexpr zint32(  ) noexcept : zval<izint32<FeatureMask>>()
        {
            ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "", "CONS()");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark sse 
         */
        constexpr zint32(__m128 value) noexcept : zval<izint32<FeatureMask>>(_mm_cvttps_epi32(value))
        {
            ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "", "CONS(__m128)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark sse 
         */
        constexpr zint32(__m128d value) noexcept : zval<izint32<FeatureMask>>(_mm_cvttpd_epi32(value))
        {
            ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "", "CONS(__m128d)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark sse 
         */
        constexpr zint32(__m128i value) noexcept : zval<izint32<FeatureMask>>(value)
        {
            ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "", "CONS(__m128i)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark sse 
         */
        constexpr zint32(int32_t value) noexcept : zval<izint32<FeatureMask>>(_mm_set1_epi32(value))
        {
            ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "", "CONS(int32_t)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark sse 
         */
        constexpr zint32(extracted_type value) noexcept : zval<izint32<FeatureMask>>(_mm_load_si128((__m128i*)value.data()))
        {
            ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "", "CONS(extracted_type)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark sse 
         */
        constexpr zint32(int32_t _3, int32_t _2, int32_t _1, int32_t _0) noexcept : zval<izint32<FeatureMask>>(_mm_set_epi32(_0, _1, _2, _3))
        {
            ZTRACE_BACKEND("sse.int32.impl", __LINE__, "int32(int32_t[4])", "", "CONS(int32_t, int32_t, int32_t, int32_t)");

        }

    };

    /// public bint32 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct bint32 :
            public detail::bint32_ops<FeatureMask>,
            public bval<ibint32<FeatureMask>>
    {
        USING_ZTYPE(ibint32<FeatureMask>);

        /// complete vector
        using zval_t = zint32<FeatureMask>;

        /// complete boolean vector
        using bval_t = bint32<FeatureMask>;

        /// Forwarding constructor
        FORWARD2(bint32, bval<ibint32<FeatureMask>>);

    };

    namespace {
        using namespace sse::int32_detail;

        static_assert(std::is_base_of<izint32 < 0>,
                      izint32 < 0 >> ::value,
                      "base_of<izint32> != izint32.");
        static_assert(!std::is_base_of<ibint32 < 0>,
                      izint32 < 0 >> ::value,
                      "base_of<izint32> == ibint32.");

        static_assert(is_zval < izint32 < 0 >> ::value,
                      "is_zval<izint32> == false.");
        static_assert(!is_bval < izint32 < 0 >> ::value,
                      "is_bval<izint32> != false.");

        static_assert(std::is_base_of<izint32 < 0>, zint32 < 0 >> ::value,
                      "base_of<zint32> != izint32.");
        static_assert(!std::is_base_of<ibint32 < 0>, zint32 < 0 >> ::value,
                      "base_of<zint32> == ibint32.");

        static_assert(zint32 < 0 > ::size == 4,
                      "zint32::size != 4.");
        static_assert(zint32 < 0 > ::alignment == 16,
                      "zint32::alignment != 16.");
        static_assert(zint32 < 0 > ::is_vector == (4 > 1),
        "zint32::is_vector != (4 > 1).");

        static_assert(std::is_same<zint32 < 0>::tag, zval_tag > ::value,
                      "zint32::tag != zval_tag.");
        static_assert(std::is_same<zint32 < 0>::vector_type, __m128i > ::value,
                      "zint32::vector_type != __m128i.");
        static_assert(std::is_same<zint32 < 0>::element_type, int32_t > ::value,
                      "zint32::element_type != int32_t.");
        static_assert(std::is_same<zint32 < 0>::mask_vector_type, __m128i > ::value,
                      "zint32::mask_vector_type != __m128i.");
        static_assert(std::is_same<zint32 < 0>::extracted_type,
                      std::array<int32_t, 4>>::value,
                      "zint32::extracted_type != std::array<int32_t, 4>.");


        static_assert(std::is_same<typename ztraits<zint32 < 0>>::tag, zval_tag > ::value,
                      "zint32::tag != zval_tag.");
        static_assert(std::is_arithmetic<typename ztraits<zint32 < 0>>::element_type > ::value,
                      "is_arithmetic<zint32::element_type> == false.");
        static_assert(is_zval < zint32 < 0 >> ::value,
                      "is_zval<zint32> == false.");
        static_assert(!is_bval < zint32 < 0 >> ::value,
                      "is_bval<zint32> != false.");


        static_assert(std::is_base_of<izint32 < 0>,
                      izint32 < 0 >> ::value,
                      "base_of<izint32> != izint32.");
        static_assert(!std::is_base_of<ibint32 < 0>,
                      izint32 < 0 >> ::value,
                      "base_of<izint32> == ibint32.");


        static_assert(!is_zval < ibint32 < 0 >> ::value,
                      "is_zval<ibint32> != false.");
        static_assert(is_bval < ibint32 < 0 >> ::value,
                      "is_bval<ibint32> == false.");

        static_assert(std::is_base_of<ibint32 < 0>, bint32 < 0 >> ::value,
                      "base_of<bint32> != ibint32.");
        static_assert(!std::is_base_of<izint32 < 0>, bint32 < 0 >> ::value,
                      "base_of<bint32> == izint32.");

        static_assert(bint32 < 0 > ::size == 4,
                      "bint32::size != 4.");
        static_assert(bint32 < 0 > ::alignment == 16,
                      "bint32::alignment != 16.");
        static_assert(bint32 < 0 > ::is_vector == (4 > 1),
        "bint32::is_vector != (4 > 1).");

        static_assert(std::is_same<bint32 < 0>::tag, bval_tag > ::value,
                      "bint32::tag != zval_tag.");
        static_assert(std::is_same<bint32 < 0>::vector_type, __m128i > ::value,
                      "bint32::vector_type != __m128i.");
        static_assert(std::is_same<bint32 < 0>::element_type, int32_t > ::value,
                      "bint32::element_type != int32_t.");
        static_assert(std::is_same<bint32 < 0>::mask_vector_type, __m128i > ::value,
                      "bint32::mask_vector_type != __m128i.");
        static_assert(std::is_same<bint32 < 0>::extracted_type,
                      std::array<int32_t, 4>>::value,
        "bint32::extracted_type != std::array<int32_t, 4>.");

        static_assert(std::is_same<typename ztraits<bint32 < 0>>::tag, bval_tag > ::value,
                      "bint32::tag != bval_tag.");
        static_assert(std::is_arithmetic<typename ztraits<bint32 < 0>>::element_type > ::value,
                      "is_arithmetic<bint32::element_type> == false.");
        static_assert(!is_zval < bint32 < 0 >> ::value,
                      "is_zval<bint32> != false.");
        static_assert(is_bval < bint32 < 0 >> ::value,
                      "is_bval<bint32> == false.");

        static_assert(!std::is_floating_point<int32_t>::value ||
                      is_floating_point < zint32 < 0 >> ::value,
                      "is_floating_point<zint32> == false. [scalar = int32_t]");
        static_assert(!std::is_floating_point<int32_t>::value ||
                      !is_integral < zint32 < 0 >> ::value,
                      "is_integral<zint32> != false. [scalar = int32_t]");

        static_assert(
                !std::is_same<int32_t, float>::value || is_float < zint32 < 0 >> ::value,
                "is_float<zint32> == false. [scalar = int32_t]");
        static_assert(
                !std::is_same<int32_t, float>::value || !is_double < zint32 < 0 >> ::value,
                "is_double<zint32> != false. [scalar = int32_t]");

        static_assert(
                !std::is_same<int32_t, double>::value || is_double < zint32 < 0 >> ::value,
                "is_double<zint32> == false. [scalar = int32_t]");
        static_assert(
                !std::is_same<int32_t, double>::value || !is_float < zint32 < 0 >> ::value,
                "is_float<zint32> != false. [scalar = int32_t]");

        static_assert(
                !std::is_integral<int32_t>::value || is_integral < zint32 < 0 >> ::value,
                "is_integral<zint32> == false. [scalar = int32_t]");
        static_assert(!std::is_integral<int32_t>::value ||
                      !is_floating_point < zint32 < 0 >> ::value,
                      "is_floating_point<zint32> != false. [scalar = int32_t]");
    }
    ///@}
}}}