//---------------------------------------------------------------------------------
//
//  This is an autogenerated file. Do not edit!
//
//---------------------------------------------------------------------------------
// The MIT License (MIT)
//
// Copyright (c) 2016 Sergej Zuyev (sergej.zuyev - at - zz-systems.net)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//---------------------------------------------------------------------------------

#pragma once

#include <type_traits>
#include <cmath>

#include "backend/intrin.hpp"
#include "backend/zval.hpp"

#include "util/type/type_composition.hpp"
#include "util/type/type_traits.hpp"

#include "util/memory.hpp"
#include "util/macros.hpp"

#include "traits/common.hpp"
#include "traits/construction.hpp"
#include "traits/construction.hpp"
#include "traits/io.hpp"
#include "traits/logical.hpp"
#include "traits/equatable.hpp"
#include "traits/io.hpp"
#include "traits/math.hpp"
#include "traits/numeric.hpp"
#include "traits/arithmetic.hpp"
#include "traits/bitwise.hpp"
#include "traits/comparable.hpp"
#include "traits/logical.hpp"
#include "traits/equatable.hpp"
#include "traits/conditional.hpp"

/**
 * @brief float32 implementation for the avx2 branch
 * provides unified access to 8 'float' values
 */

namespace zacc { namespace backend { namespace avx2 {

    template<uint64_t features>
    struct bfloat32;

    template<uint64_t features>
    struct zfloat32;


    // =================================================================================================================
    /**
     * @name construction operations
     */
    ///@{

    /**
     * @brief construction
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_construction
    {

        /**
         * @brief construction basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;



            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl() : base_t() {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "CONS()");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(__m256 value) : base_t(value) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "CONS(__m256 value)");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(__m256d value) : base_t(_mm256_castps128_ps256(_mm256_cvtpd_ps(value))) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "CONS(__m256d value)");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(__m256i value) : base_t(_mm256_cvtepi32_ps(value)) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "CONS(__m256i value)");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(float value) : base_t(_mm256_set1_ps(value)) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "CONS(float value)");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(std::array<typename base_t::element_t, base_t::size()> value) : base_t(_mm256_loadu_ps(value.data())) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "CONS(std::array<typename base_t::elem..)");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(float arg7, float arg6, float arg5, float arg4, float arg3, float arg2, float arg1, float arg0) : base_t(_mm256_set_ps(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7)) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "CONS(float arg7, float arg6, float ar..)");

            }

        };

        /**
         * @brief construction public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::construction<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::construction<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name construction operations
     */
    ///@{

    /**
     * @brief construction
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct bfloat32_construction
    {

        /**
         * @brief construction basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl() : base_t() {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(__m256 value) : base_t(value) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(__m256d value) : base_t(_mm256_castpd_ps(value)) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "");

            }


            /**
             * @brief construction default branch
             * @relates float32
             * @remark avx2 - default
             */
            constexpr __impl(__m256i value) : base_t(_mm256_castsi256_ps(value)) {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "");

            }

        };

        /**
         * @brief construction public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::construction<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::construction<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name io operations
     */
    ///@{

    /**
     * @brief io
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct bfloat32_io
    {

        /**
         * @brief io basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief io default branch
             * @relates float32
             * @remark avx2 - default
             */
            template<typename OutputIt> friend void vstore(OutputIt result, composed_t input)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "vstore");

                _mm256_storeu_ps(result, input);
            }


            /**
             * @brief io default branch
             * @relates float32
             * @remark avx2 - default
             */
            template<typename OutputIt> friend void vstream(OutputIt result, composed_t input)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "vstream");

                _mm256_stream_ps(result, input);
            }


            /**
             * @brief io default branch
             * @relates float32
             * @remark avx2 - default
             */
            template<typename RandomIt> friend zfloat32<base_t::features> vgather(RandomIt input, const zint32<base_t::features> &index, composed_t)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "vgather");

                return _mm256_i32gather_ps(input, index, 4);
            }

        };

        /**
         * @brief io public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::io<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::io<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name logical operations
     */
    ///@{

    /**
     * @brief logical
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct bfloat32_logical
    {

        /**
         * @brief logical basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief logical default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vlneg(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "vlneg");

                return _mm256_cmp_ps(one, _mm256_setzero_ps(), _CMP_EQ_OQ);
            }


            /**
             * @brief logical default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vlor(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "vlor");

                return _mm256_or_ps(one, other);
            }


            /**
             * @brief logical default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vland(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "vland");

                return _mm256_and_ps(one, other);
            }

        };

        /**
         * @brief logical public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::logical<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::logical<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name equatable operations
     */
    ///@{

    /**
     * @brief equatable
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct bfloat32_equatable
    {

        /**
         * @brief equatable basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief equatable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> veq(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "veq");

                return _mm256_cmp_ps(one, other, _CMP_EQ_OQ);
            }


            /**
             * @brief equatable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vneq(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "bfloat32(float[8])", "default", "vneq");

                return _mm256_cmp_ps(one, other, _CMP_NEQ_OQ);
            }

        };

        /**
         * @brief equatable public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::equatable<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::equatable<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name io operations
     */
    ///@{

    /**
     * @brief io
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_io
    {

        /**
         * @brief io basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief io default branch
             * @relates float32
             * @remark avx2 - default
             */
            template<typename OutputIt> friend void vstore(OutputIt result, composed_t input)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vstore");

                _mm256_storeu_ps(result, input);
            }


            /**
             * @brief io default branch
             * @relates float32
             * @remark avx2 - default
             */
            template<typename OutputIt> friend void vstream(OutputIt result, composed_t input)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vstream");

                _mm256_stream_ps(result, input);
            }


            /**
             * @brief io default branch
             * @relates float32
             * @remark avx2 - default
             */
            template<typename RandomIt> friend zfloat32<base_t::features> vgather(RandomIt input, const zint32<base_t::features> &index, composed_t)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vgather");

                return _mm256_i32gather_ps(input, index, 4);
            }

        };

        /**
         * @brief io public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::io<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::io<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name math operations
     */
    ///@{

    /**
     * @brief math
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_math
    {

        /**
         * @brief math basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vabs(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vabs");

                return _mm256_max_ps(one, _mm256_sub_ps(_mm256_setzero_ps(), one));
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vmin(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vmin");

                return _mm256_min_ps(one, other);
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vmax(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vmax");

                return _mm256_max_ps(one, other);
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vclamp(composed_t self, composed_t from, composed_t to)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vclamp");

                return vmin(to, vmax(from, self));
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vrcp(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vrcp");

                return (1/one);
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vtrunc(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vtrunc");

                return _mm256_cvtepi32_ps(_mm256_cvttps_epi32(one));
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vfloor(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vfloor");

                return _mm256_floor_ps(one);
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vceil(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vceil");

                return _mm256_ceil_ps(one);
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vround(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vround");

                return _mm256_round_ps (one, _MM_FROUND_TO_NEAREST_INT |_MM_FROUND_NO_EXC);
            }


            /**
             * @brief math default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vsqrt(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vsqrt");

                return _mm256_sqrt_ps(one);
            }

        };

        /**
         * @brief math public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::math<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::math<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name numeric operations
     */
    ///@{

    /**
     * @brief numeric
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_numeric
    {

        /**
         * @brief numeric basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);

        };

        /**
         * @brief numeric public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::numeric<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::numeric<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name arithmetic operations
     */
    ///@{

    /**
     * @brief arithmetic
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_arithmetic
    {

        /**
         * @brief arithmetic basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief arithmetic default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vneg(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vneg");

                return _mm256_sub_ps(_mm256_setzero_ps(), one);
            }


            /**
             * @brief arithmetic default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vadd(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vadd");

                return _mm256_add_ps(one, other);
            }


            /**
             * @brief arithmetic default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vsub(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vsub");

                return _mm256_sub_ps(one, other);
            }


            /**
             * @brief arithmetic default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vmul(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vmul");

                return _mm256_mul_ps(one, other);
            }


            /**
             * @brief arithmetic default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vdiv(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vdiv");

                return _mm256_div_ps(one, other);
            }


            /**
             * @brief arithmetic default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vfmadd(composed_t multiplicand, composed_t multiplier, composed_t addendum)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vfmadd");

                return _mm256_fmadd_ps (multiplicand, multiplier, addendum);
            }


            /**
             * @brief arithmetic default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vfmsub(composed_t multiplicand, composed_t multiplier, composed_t addendum)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vfmsub");

                return _mm256_fmsub_ps(multiplicand, multiplier, addendum);
            }

        };

        /**
         * @brief arithmetic public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::arithmetic<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::arithmetic<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name bitwise operations
     */
    ///@{

    /**
     * @brief bitwise
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_bitwise
    {

        /**
         * @brief bitwise basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief bitwise default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vbneg(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vbneg");

                auto zero = _mm256_setzero_ps();
                auto ones = _mm256_cmp_ps(zero, zero, _CMP_EQ_OQ);
                return _mm256_xor_ps(one, ones);
            }


            /**
             * @brief bitwise default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vband(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vband");

                return _mm256_and_ps(one, other);
            }


            /**
             * @brief bitwise default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vbor(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vbor");

                return _mm256_or_ps(one, other);
            }


            /**
             * @brief bitwise default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vbxor(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vbxor");

                return _mm256_xor_ps(one, other);
            }


            /**
             * @brief bitwise avx2 branch
             * @relates float32
             * @remark avx2 - avx2
             */
            template<typename T = bool> friend std::enable_if_t<is_eligible_v<base_t, capabilities::AVX2>, T> is_set(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "avx2", "is_set");

                auto ival =  _mm256_castps_si256(one);
                return _mm256_testc_si256(ival, _mm256_cmpeq_epi32(ival,ival));
            }


            /**
             * @brief bitwise default branch
             * @relates float32
             * @remark avx2 - default
             */
            template<typename T = bool> friend std::enable_if_t<!is_eligible_v<base_t, capabilities::AVX2>, T> is_set(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "is_set");

                auto hi = _mm_castps_si128(_mm256_extractf128_ps(one, 1));
                auto lo = _mm_castps_si128(_mm256_extractf128_ps(one, 0));
                return _mm_test_all_ones(hi) != 0 && _mm_test_all_ones(lo) != 0;
            }

        };

        /**
         * @brief bitwise public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::bitwise<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::bitwise<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name comparable operations
     */
    ///@{

    /**
     * @brief comparable
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_comparable
    {

        /**
         * @brief comparable basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief comparable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vgt(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vgt");

                return _mm256_cmp_ps(one, other, _CMP_GT_OQ);
            }


            /**
             * @brief comparable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vlt(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vlt");

                return _mm256_cmp_ps(one, other, _CMP_LT_OQ);
            }


            /**
             * @brief comparable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vge(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vge");

                return _mm256_cmp_ps(one, other, _CMP_GE_OQ);
            }


            /**
             * @brief comparable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vle(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vle");

                return _mm256_cmp_ps(one, other, _CMP_LE_OQ);
            }

        };

        /**
         * @brief comparable public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::comparable<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::comparable<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name logical operations
     */
    ///@{

    /**
     * @brief logical
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_logical
    {

        /**
         * @brief logical basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief logical default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vlneg(composed_t one)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vlneg");

                return _mm256_cmp_ps(one, _mm256_setzero_ps(), _CMP_EQ_OQ);
            }


            /**
             * @brief logical default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vlor(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vlor");

                return _mm256_or_ps(one, other);
            }


            /**
             * @brief logical default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vland(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vland");

                return _mm256_and_ps(one, other);
            }

        };

        /**
         * @brief logical public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::logical<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::logical<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name equatable operations
     */
    ///@{

    /**
     * @brief equatable
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_equatable
    {

        /**
         * @brief equatable basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief equatable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> veq(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "veq");

                return _mm256_cmp_ps(one, other, _CMP_EQ_OQ);
            }


            /**
             * @brief equatable default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend bfloat32<base_t::features> vneq(composed_t one, composed_t other)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vneq");

                return _mm256_cmp_ps(one, other, _CMP_NEQ_OQ);
            }

        };

        /**
         * @brief equatable public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::equatable<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::equatable<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // =================================================================================================================
    /**
     * @name conditional operations
     */
    ///@{

    /**
     * @brief conditional
     * @relates float32
     * @remark avx2
     */
    template<typename composed_t>
    struct zfloat32_conditional
    {

        /**
         * @brief conditional basic interface implementation
         * @relates float32
         * @remark avx2
         */
        template<typename base_t>
        struct __impl : base_t
        {
            using zval_t        = zfloat32<base_t::features>;
            using bval_t        = bfloat32<base_t::features>;
            using vector_t      = typename zval_traits<base_t>::vector_t;
            using element_t     = typename zval_traits<base_t>::element_t;
            using mask_vector_t = typename zval_traits<base_t>::mask_vector_t;
            using extracted_t   = typename zval_traits<base_t>::extracted_t;

            FORWARD(__impl);


            /**
             * @brief conditional default branch
             * @relates float32
             * @remark avx2 - default
             */
            friend zfloat32<base_t::features> vsel(composed_t condition, composed_t if_value, composed_t else_value)  noexcept {

                ZTRACE_BACKEND("avx2.float32.impl", __LINE__, "zfloat32(float[8])", "default", "vsel");

                auto mask = _mm256_cmp_ps(_mm256_setzero_ps(), condition, _CMP_EQ_OQ);
                return _mm256_blendv_ps(if_value, else_value, mask);
            }

        };

        /**
         * @brief conditional public interface implementation
         * @relates float32
         * @remark avx2
         */

        template<typename base_t>
        using zimpl = traits::conditional<__impl<base_t>, zfloat32<base_t::features>>;

        template<typename base_t>
        using bimpl = traits::conditional<__impl<base_t>, bfloat32<base_t::features>>;


    };

    ///@}


    // Type composition ================================================================================================

    /**
     * @name float32 composition
     */
    ///@{

    //namespace composition {

        /**
         * @brief zval parametrization using
         * - '__m256' as underlying vector type
         * - 'float' as scalar type
         * - '8' as vector size
         * - '32' as alignment
         * @relates float32
         * @remark avx2
         */
        template<uint64_t features>
        struct __zval_float32
        {
            using zval_t = zval<__m256, __m256, float, zval_tag, 8, 32, features>;
            using bval_t = bval<__m256, __m256, 8, 32, features>;

            struct impl : public zval_t
            {
                FORWARD2(impl, zval_t);
            };
        };
        /**
         * @brief zval composition
         * @relates float32
         * @remark avx2
         */
        template<uint64_t features>
        struct __zfloat32
        {
            struct impl;

            using zval_t = typename __zval_float32<features>::impl;
            using composition_t = compose
            <
                printable::impl,
                iteratable::impl,
                convertable::impl,
                zfloat32_io<impl>::template zimpl,
                zfloat32_math<impl>::template zimpl,
                zfloat32_numeric<impl>::template zimpl,
                zfloat32_arithmetic<impl>::template zimpl,
                zfloat32_bitwise<impl>::template zimpl,
                zfloat32_comparable<impl>::template zimpl,
                zfloat32_logical<impl>::template zimpl,
                zfloat32_equatable<impl>::template zimpl,
                zfloat32_conditional<impl>::template zimpl,
                zfloat32_construction<impl>::template zimpl,

                composable<zval_t>::template type
            >;

            struct impl : public composition_t
            {
                FORWARD2(impl, composition_t);
            };
        };

        /**
         * @brief bval parametrization using
         * - '__m256' as underlying vector type
         * - 'float' as scalar type
         * - '8' as vector size
         * - '32' as alignment
         * @relates float32
         * @remark avx2
         */
        template<uint64_t features>
        struct __bval_float32
        {
            using zval_t = zval<__m256, __m256, float, zval_tag, 8, 32, features>;
            using bval_t = bval<__m256, __m256, 8, 32, features>;

            struct impl : public bval_t
            {
                FORWARD2(impl, bval_t);
            };
        };

        template<uint64_t features>
        struct __bfloat32
        {
            struct impl;

            using bval_t = typename __bval_float32<features>::impl;
            using composition_t = compose
            <
                printable::impl,
                iteratable::impl,
                convertable::impl,
                bfloat32_io<impl>::template bimpl,
                bfloat32_logical<impl>::template bimpl,
                bfloat32_equatable<impl>::template bimpl,
                bfloat32_construction<impl>::template bimpl,

                composable<bval_t>::template type
            >;

            struct impl : public composition_t
            {
                FORWARD2(impl, composition_t);
            };
        };
    //}

    template<uint64_t features>
    struct zfloat32 : public /*composition::*/__zfloat32<features>::impl
    {
        FORWARD2(zfloat32, /*composition::*/__zfloat32<features>::impl);
    };

    template<uint64_t features>
    struct bfloat32 : public /*composition::*/__bfloat32<features>::impl
    {
        FORWARD2(bfloat32, /*composition::*/__bfloat32<features>::impl);
    };

    static_assert(is_zval<zfloat32<0>>::value, "is_zval for zfloat32 failed.");
    static_assert(is_bval<bfloat32<0>>::value, "is_bval for bfloat32 failed.");

    static_assert(is_floating_point<zfloat32<0>>::value, "is_floating_point for zfloat32 failed.");
    static_assert(!is_integral<zfloat32<0>>::value, "is_integral for zfloat32 failed.");

    static_assert(is_float<zfloat32<0>>::value, "is_float for zfloat32 failed.");
    static_assert(!is_double<zfloat32<0>>::value, "is_double for zfloat32 failed.");

    ///@}
}}}