//---------------------------------------------------------------------------------
// The MIT License (MIT)
//
// Copyright (c) 2015-2018 Sergej Zuyev (sergej.zuyev - at - zz-systems.net)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//---------------------------------------------------------------------------------

/**
 * @file int32.impl.hpp
 * @brief
 * This file provides defines required components and logic for int32 avx2 target.
 * Provides unified access to 8 'int32_t' values
 * @remark
 * This is an autogenerated file. Changes will be lost on regeneration.
 */
#pragma once

#include <type_traits>
#include <cmath>

#include "backend/intrin.hpp"
#include "backend/zval.hpp"

#include "util/type/type_composition.hpp"
#include "util/type/type_traits.hpp"

#include "util/memory.hpp"
#include "util/macros.hpp"

#include "traits/convertable.hpp"
#include "traits/printable.hpp"
#include "traits/equatable.hpp"
#include "traits/math.hpp"
#include "traits/numeric.hpp"
#include "traits/arithmetic.hpp"
#include "traits/logical.hpp"
#include "traits/conditional.hpp"
#include "traits/comparable.hpp"
#include "traits/bitwise.hpp"
#include "traits/bitwise_shift.hpp"
#include "traits/io.hpp"

namespace zacc { namespace backend { namespace avx2
{
    /// @cond
    template<uint64_t features>
    struct bint32;

    template<uint64_t features>
    struct zint32;
    /// @endcond

    namespace int32_detail
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// memory alignment
        static constexpr size_t alignment = 32;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m256i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = int32_t;

        /// mask type for boolean operations
        using mask_vector_t = __m256i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /**
         * @brief zval parametrization using
         * - '__m256i' as underlying vector type
         * - 'int32_t' as scalar type
         * - '8' as vector size
         * - '32' as alignment
         * @relates int32
         * @remark avx2
         */
        template<uint64_t Features>
        using zval_base = zval<__m256i, __m256i, int32_t, zval_tag, 8, 32, Features>;

        /**
         * @brief bval parametrization using
         * - '__m256i' as underlying vector type
         * - 'int32_t' as scalar type
         * - '8' as vector size
         * - '32' as alignment
         * @relates int32
         * @remark avx2
        */
        template<uint64_t Features>
        using bval_base = bval<__m256i, __m256i, int32_t, 8, 32, Features>;
    }
}}}

namespace zacc {

    template<typename T>
    struct ztraits<T, std::enable_if_t<
            std::is_base_of<backend::avx2::int32_detail::zval_base<T::feature_mask>, T>::value
            || std::is_base_of<backend::avx2::int32_detail::bval_base<T::feature_mask>, T>::value>>
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// capabilities
        static constexpr uint64_t feature_mask = T::feature_mask;

        /// memory alignment
        static constexpr size_t alignment = 32;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m256i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = int32_t;

        /// mask type for boolean operations
        using mask_vector_t = __m256i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        using zval_t = backend::avx2::zint32<T::feature_mask>;
        using bval_t = backend::avx2::bint32<T::feature_mask>;

        using tag = select_t<
                when<std::is_base_of<backend::avx2::int32_detail::zval_base<T::feature_mask>, T>::value, zval_tag>,
                when<std::is_base_of<backend::avx2::int32_detail::bval_base<T::feature_mask>, T>::value, bval_tag>>;
    };
}

namespace zacc { namespace backend { namespace avx2 {

    namespace int32_detail {

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_io
        {
            /**
             * @brief io basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates int32
                 * @remark avx2 default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vstore");

                    _mm256_store_si256((__m256i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark avx2 default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vstream");

                    _mm256_stream_si256((__m256i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark avx2 default
                 */
                template<typename RandomIt> friend zint32<Interface::feature_mask> vgather(RandomIt input, const zint32<Interface::feature_mask> &index,  Composed) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vgather");

                    return _mm256_i32gather_epi32(&(*input), index, 4);
                }

            };

            /**
             * @brief io public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name math modules
         */
        ///@{
        /**
         * @brief math
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_math
        {
            /**
             * @brief math basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief math default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vabs(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vabs");

                    return _mm256_abs_epi32(one);
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vmin(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vmin");

                    return _mm256_min_epi32(one, other);
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vmax(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vmax");

                    return _mm256_max_epi32(one, other);
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vclamp(Composed self, Composed from, Composed to) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vclamp");

                    return vmin(to, vmax(from, self));
                }


                /**
                 * @brief math default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vsqrt(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vsqrt");

                    return _mm256_sqrt_ps(_mm256_cvtepi32_ps(one));
                }

            };

            /**
             * @brief math public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::math<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name numeric modules
         */
        ///@{
        /**
         * @brief numeric
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_numeric
        {
            /**
             * @brief numeric basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {
            };

            /**
             * @brief numeric public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::numeric<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name arithmetic modules
         */
        ///@{
        /**
         * @brief arithmetic
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_arithmetic
        {
            /**
             * @brief arithmetic basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vneg(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vneg");

                    return _mm256_sub_epi32(_mm256_setzero_si256(), one);
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vadd(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vadd");

                    return _mm256_add_epi32(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vsub(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vsub");

                    return _mm256_sub_epi32(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vmul(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vmul");

                    return _mm256_mullo_epi32(one, other);
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vdiv(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vdiv");

                    return _mm256_div_ps(_mm256_cvtepi32_ps(one), _mm256_cvtepi32_ps(other));
                }


                /**
                 * @brief arithmetic default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vmod(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vmod");

                    return vsub(one, vmul(other, vdiv(one, other)));
                }

            };

            /**
             * @brief arithmetic public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::arithmetic<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbneg");

                    auto zero = _mm256_setzero_si256();
                    auto ones = _mm256_cmpeq_epi32(zero, zero);
                    return _mm256_xor_si256(one, ones);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vband");

                    return _mm256_and_si256(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbor");

                    return _mm256_or_si256(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbxor");

                    return _mm256_xor_si256(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bool is_set(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "is_set");

                    return _mm256_testc_si256(one, _mm256_cmpeq_epi32(one,one));
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise_shift modules
         */
        ///@{
        /**
         * @brief bitwise_shift
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_bitwise_shift
        {
            /**
             * @brief bitwise_shift basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vbsll(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbsll");

                    return _mm256_sll_epi32(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vbsrl(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbsrl");

                    return _mm256_srl_epi32(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vbslli(const Composed one, const size_t other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbslli");

                    return _mm256_slli_epi32(one, other);
                }


                /**
                 * @brief bitwise_shift default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vbsrli(const Composed one, const size_t other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbsrli");

                    return _mm256_srli_epi32(one, other);
                }

            };

            /**
             * @brief bitwise_shift public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::bitwise_shift<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name comparable modules
         */
        ///@{
        /**
         * @brief comparable
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_comparable
        {
            /**
             * @brief comparable basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vgt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vgt");

                    return { _mm256_cmpgt_epi32(one, other), last_operation::comparison };
                }


                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vlt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vlt");

                    return { _mm256_cmpgt_epi32(other, one), last_operation::comparison };
                }


                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vge(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vge");

                    return !(one < other);
                }


                /**
                 * @brief comparable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vle(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vle");

                    return !(one > other);
                }

            };

            /**
             * @brief comparable public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::comparable<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vlneg");

                    return { _mm256_cmpeq_epi32(one, _mm256_setzero_si256()), last_operation::logic };
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vlor");

                    return { _mm256_or_si256(one, other), last_operation::logic };
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vland");

                    return { _mm256_and_si256(one, other), last_operation::logic };
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "veq");

                    return { _mm256_cmpeq_epi32(one, other), last_operation::comparison };
                }


                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vneq");

                    return !(one == other);
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name conditional modules
         */
        ///@{
        /**
         * @brief conditional
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct zint32_conditional
        {
            /**
             * @brief conditional basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief conditional default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend zint32<Interface::feature_mask> vsel(bint32<Interface::feature_mask> condition, Composed if_value, Composed else_value) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vsel");

                    return _mm256_blendv_epi8(else_value, if_value, condition);
                }

            };

            /**
             * @brief conditional public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::conditional<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct bint32_io
        {
            /**
             * @brief io basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates int32
                 * @remark avx2 default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vstore");

                    _mm256_store_si256((__m256i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark avx2 default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vstream");

                    _mm256_stream_si256((__m256i*)&(*result), input);
                }


                /**
                 * @brief io default
                 * @relates int32
                 * @remark avx2 default
                 */
                template<typename RandomIt> friend bint32<Interface::feature_mask> vgather(RandomIt input, const zint32<Interface::feature_mask> &index,  Composed) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vgather");

                    return _mm256_i32gather_epi32(&(*input), index, 4);
                }

            };

            /**
             * @brief io public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct bint32_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbneg");

                    auto zero = _mm256_setzero_si256();
                    auto ones = _mm256_cmpeq_epi32(zero, zero);
                    return _mm256_xor_si256(one, ones);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vband");

                    return _mm256_and_si256(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbor");

                    return _mm256_or_si256(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vbxor");

                    return _mm256_xor_si256(one, other);
                }


                /**
                 * @brief bitwise default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bool is_set(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "is_set");

                    return _mm256_testc_si256(one, _mm256_cmpeq_epi32(one,one));
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct bint32_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vlneg");

                    return { _mm256_cmpeq_epi32(one, _mm256_setzero_si256()), last_operation::logic };
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vlor");

                    return { _mm256_or_si256(one, other), last_operation::logic };
                }


                /**
                 * @brief logical default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vland");

                    return { _mm256_and_si256(one, other), last_operation::logic };
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates int32
         * @remark avx2
         */
        template<typename Interface, typename Composed>
        struct bint32_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates int32
             * @remark avx2
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "veq");

                    return { _mm256_cmpeq_epi32(one, other), last_operation::comparison };
                }


                /**
                 * @brief equatable default
                 * @relates int32
                 * @remark avx2 default
                 */
                friend bint32<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "default", "vneq");

                    return !(one == other);
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates int32
             * @remark avx2
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bint32<Interface::feature_mask>>;
        };

        ///@}


        // Type composition ================================================================================================

        /**
         * @name int32 composition
         */
        ///@{

        /**
         * @brief zval composition
         * @relates int32
         * @remark avx2
         * @tparam features feature mask
         */
        template<uint64_t FeatureMask>
        using __zint32 = compose_t
        <
            printable<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            convertable<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_io<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_math<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_numeric<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_arithmetic<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_bitwise<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_bitwise_shift<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_comparable<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_logical<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_equatable<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl,
            zint32_conditional<zval_base<FeatureMask>, zint32<FeatureMask>>::template impl
        >;

        /// bint32 composition
        /// @tparam features feature mask
        template<uint64_t FeatureMask>
        using __bint32 = compose_t
        <
            printable<bval_base<FeatureMask>, bint32<FeatureMask>>::template impl,
            convertable<bval_base<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_io<bval_base<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_bitwise<bval_base<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_logical<bval_base<FeatureMask>, bint32<FeatureMask>>::template impl,
            bint32_equatable<bval_base<FeatureMask>, bint32<FeatureMask>>::template impl
        >;

        ///@}
    } // end namespace

    /// public zint32 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct zint32 :
            public int32_detail::__zint32<FeatureMask>,
            public int32_detail::zval_base<FeatureMask>
    {
        /// type tag
        using tag = zval_tag;

        /// complete vector
        using zval_t = zint32<FeatureMask>;

        /// complete boolean vector
        using bval_t = bint32<FeatureMask>;

        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// memory alignment
        static constexpr size_t alignment = 32;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m256i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = int32_t;

        /// mask type for boolean operations
        using mask_vector_t = __m256i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /**
         * copy constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<std::is_convertible<T, __m256i>::value>>// || std::is_convertible<T, int32_t>::value>>
        constexpr zint32(const T& other) noexcept
                : int32_detail::zval_base<FeatureMask>(other)
        {}

        /**
         * move constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<(size > 1) && std::is_convertible<T, __m256i>::value>>
        constexpr zint32(T&& other) noexcept
            : int32_detail::zval_base<FeatureMask>(std::forward<T>(other))
        {}

        /**
         * copy constructor
         * @param other
         */
        constexpr zint32(const bint32<FeatureMask>& other) noexcept
            : int32_detail::zval_base<FeatureMask>(other.value())
        {}


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr zint32(  ) noexcept : int32_detail::zval_base<FeatureMask>()
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS()");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr zint32(__m256 value) noexcept : int32_detail::zval_base<FeatureMask>(_mm256_cvttps_epi32(value))
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS(__m256)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr zint32(__m256d value) noexcept : int32_detail::zval_base<FeatureMask>(_mm256_castsi128_si256(_mm256_cvttpd_epi32(value)))
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS(__m256d)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr zint32(__m256i value) noexcept : int32_detail::zval_base<FeatureMask>(value)
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS(__m256i)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr zint32(int32_t value) noexcept : int32_detail::zval_base<FeatureMask>(_mm256_set1_epi32(value))
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS(int32_t)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr zint32(extracted_t value) noexcept : int32_detail::zval_base<FeatureMask>(_mm256_load_si256((__m256i*)value.data()))
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS(extracted_t)");

        }


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr zint32(int32_t _7, int32_t _6, int32_t _5, int32_t _4, int32_t _3, int32_t _2, int32_t _1, int32_t _0) noexcept : int32_detail::zval_base<FeatureMask>(_mm256_set_epi32(_0, _1, _2, _3, _4, _5, _6, _7))
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t)");

        }

    };

    /// public bint32 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct bint32 :
            public int32_detail::__bint32<FeatureMask>,
            public int32_detail::bval_base<FeatureMask>
    {
        /// type tag
        using tag = bval_tag;

        /// complete vector
        using zval_t = zint32<FeatureMask>;

        /// complete boolean vector
        using bval_t = bint32<FeatureMask>;

        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 8;

        /// memory alignment
        static constexpr size_t alignment = 32;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = __m256i;

        /// scalar type, like int for sse 4x integer vector
        using element_t = bool;

        /// mask type for boolean operations
        using mask_vector_t = __m256i;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /// Forwarding constructor
        FORWARD2(bint32, int32_detail::bval_base<FeatureMask>);


        /**
         * @brief constructable 
         * @relates int32
         * @remark avx2 
         */
        constexpr bint32(  ) noexcept : int32_detail::bval_base<FeatureMask>()
        {
            ZTRACE_BACKEND("avx2.int32.impl", __LINE__, "int32(int32_t[8])", "", "CONS()");

        }

    };

    static_assert(is_zval<zint32<0>>::value, "is_zval for zint32 failed.");
    static_assert(is_bval<bint32<0>>::value, "is_bval for bint32 failed.");

    static_assert(!is_floating_point<zint32<0>>::value, "is_floating_point for zint32 failed.");
    static_assert(is_integral<zint32<0>>::value, "is_integral for zint32 failed.");

    static_assert(!is_float<zint32<0>>::value, "is_float for zint32 failed.");
    static_assert(!is_double<zint32<0>>::value, "is_double for zint32 failed.");

    ///@}
}}}