#!/usr/bin/env bash

cd ${TRAVIS_BUILD_DIR}
export CXX=${COMPILER}
cmake -H../zacc -B${BUILD_DIR} -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DBUILD_SANITIZE_MEMORY=${BUILD_SANITIZE_MEMORY} -DBUILD_DOCUMENTATION=${DOC_BUILDER}
cd ${BUILD_DIR}