//---------------------------------------------------------------------------------
// The MIT License (MIT)
//
// Copyright (c) 2015-2018 Sergej Zuyev (sergej.zuyev - at - zz-systems.net)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//---------------------------------------------------------------------------------

/**
 * @file float32.impl.hpp
 * @brief
 * This file provides defines required components and logic for float32 scalar target.
 * Provides unified access to 1 'float' values
 * @remark
 * This is an autogenerated file. Changes will be lost on regeneration.
 */
#pragma once

#include <type_traits>
#include <cmath>

#include "backend/intrin.hpp"
#include "backend/zval.hpp"

#include "util/type/type_composition.hpp"
#include "util/type/type_traits.hpp"

#include "util/memory.hpp"
#include "util/macros.hpp"

#include "traits/convertable.hpp"
#include "traits/printable.hpp"
#include "traits/conditional.hpp"
#include "traits/numeric.hpp"
#include "traits/bitwise.hpp"
#include "traits/comparable.hpp"
#include "traits/io.hpp"
#include "traits/arithmetic.hpp"
#include "traits/equatable.hpp"
#include "traits/logical.hpp"
#include "traits/math.hpp"

namespace zacc { namespace backend { namespace scalar
{
    /// @cond
    template<uint64_t features>
    struct bfloat32;

    template<uint64_t features>
    struct zfloat32;
    /// @endcond

    namespace float32_detail
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 1;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = std::array<float, 1>;

        /// scalar type, like int for sse 4x integer vector
        using element_t = float;

        /// mask type for boolean operations
        using mask_vector_t = std::array<bool, 1>;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /**
         * @brief zval parametrization using
         * - 'std::array<float, 1>' as underlying vector type
         * - 'float' as scalar type
         * - '1' as vector size
         * - '16' as alignment
         * @relates float32
         * @remark scalar
         */
        template<uint64_t Features>
        using zval_base = zval<std::array<float, 1>, std::array<bool, 1>, float, zval_tag, 1, 16, Features>;

        /**
         * @brief bval parametrization using
         * - 'std::array<float, 1>' as underlying vector type
         * - 'float' as scalar type
         * - '1' as vector size
         * - '16' as alignment
         * @relates float32
         * @remark scalar
        */
        template<uint64_t Features>
        using bval_base = bval<std::array<float, 1>, std::array<bool, 1>, float, 1, 16, Features>;
    }
}}}

namespace zacc {

    template<typename T>
    struct ztraits<T, std::enable_if_t<
            std::is_base_of<backend::scalar::float32_detail::zval_base<T::feature_mask>, T>::value
            || std::is_base_of<backend::scalar::float32_detail::bval_base<T::feature_mask>, T>::value>>
    {
        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 1;

        /// capabilities
        static constexpr uint64_t feature_mask = T::feature_mask;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = std::array<float, 1>;

        /// scalar type, like int for sse 4x integer vector
        using element_t = float;

        /// mask type for boolean operations
        using mask_vector_t = std::array<bool, 1>;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        using zval_t = backend::scalar::zfloat32<T::feature_mask>;
        using bval_t = backend::scalar::bfloat32<T::feature_mask>;

        using tag = select_t<
                when<std::is_base_of<backend::scalar::float32_detail::zval_base<T::feature_mask>, T>::value, zval_tag>,
                when<std::is_base_of<backend::scalar::float32_detail::bval_base<T::feature_mask>, T>::value, bval_tag>>;
    };
}

namespace zacc { namespace backend { namespace scalar {

    namespace float32_detail {

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_io
        {
            /**
             * @brief io basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates float32
                 * @remark scalar default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vstore");

                    result[0] = input.value();
                }


                /**
                 * @brief io default
                 * @relates float32
                 * @remark scalar default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vstream");

                    result[0] = input.value();
                }


                /**
                 * @brief io default
                 * @relates float32
                 * @remark scalar default
                 */
                template<typename RandomIt> friend zfloat32<Interface::feature_mask> vgather(RandomIt input, const zint32<Interface::feature_mask> &index,  Composed) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vgather");

                    return input[index.value()];
                }

            };

            /**
             * @brief io public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name math modules
         */
        ///@{
        /**
         * @brief math
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_math
        {
            /**
             * @brief math basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vabs(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vabs");

                    return std::abs(one.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vmin(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vmin");

                    return std::min(one.value(), other.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vmax(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vmax");

                    return std::max(one.value(), other.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vclamp(Composed self, Composed from, Composed to) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vclamp");

                    return vmin(to, vmax(from, self));
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vrcp(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vrcp");

                    return (1 / one.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vtrunc(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vtrunc");

                    return std::trunc(one.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vfloor(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vfloor");

                    return std::floor(one.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vceil(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vceil");

                    return std::ceil(one.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vround(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vround");

                    return std::round(one.value());
                }


                /**
                 * @brief math default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vsqrt(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vsqrt");

                    return std::sqrt(one.value());
                }

            };

            /**
             * @brief math public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::math<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name numeric modules
         */
        ///@{
        /**
         * @brief numeric
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_numeric
        {
            /**
             * @brief numeric basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {
            };

            /**
             * @brief numeric public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::numeric<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name arithmetic modules
         */
        ///@{
        /**
         * @brief arithmetic
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_arithmetic
        {
            /**
             * @brief arithmetic basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief arithmetic default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vneg(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vneg");

                    return (-one.value());
                }


                /**
                 * @brief arithmetic default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vadd(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vadd");

                    return (one.value() + other.value());
                }


                /**
                 * @brief arithmetic default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vsub(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vsub");

                    return (one.value() - other.value());
                }


                /**
                 * @brief arithmetic default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vmul(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vmul");

                    return (one.value() * other.value());
                }


                /**
                 * @brief arithmetic default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vdiv(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vdiv");

                    return (one.value() / other.value());
                }


                /**
                 * @brief arithmetic default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vfmadd(Composed multiplicand, Composed multiplier, Composed addendum) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vfmadd");

                    return multiplicand.value() * multiplier.value() + addendum.value();
                }


                /**
                 * @brief arithmetic default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vfmsub(Composed multiplicand, Composed multiplier, Composed addendum) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vfmsub");

                    return multiplicand.value() * multiplier.value() - addendum.value();
                }

            };

            /**
             * @brief arithmetic public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::arithmetic<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vbneg");

                    auto _one = one.value();
                    float result;
                    bitsof(result) = ~bitsof(_one);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vband");

                    auto _one = one.value();
                    auto _other = other.value();
                    float result;
                    bitsof(result) = bitsof(_one) & bitsof(_other);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vbor");

                    auto _one = one.value();
                    auto _other = other.value();
                    float result;
                    bitsof(result) = bitsof(_one) | bitsof(_other);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vbxor");

                    auto _one = one.value();
                    auto _other = other.value();
                    float result;
                    bitsof(result) = bitsof(_one) ^ bitsof(_other);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bool is_set(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "is_set");

                    return one.value() != 0;
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name comparable modules
         */
        ///@{
        /**
         * @brief comparable
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_comparable
        {
            /**
             * @brief comparable basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief comparable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vgt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vgt");

                    return (one.value() > other.value());
                }


                /**
                 * @brief comparable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vlt(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vlt");

                    return (one.value() < other.value());
                }


                /**
                 * @brief comparable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vge(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vge");

                    return (one.value() >= other.value());
                }


                /**
                 * @brief comparable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vle(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vle");

                    return (one.value() <= other.value());
                }

            };

            /**
             * @brief comparable public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::comparable<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vlneg");

                    return !one.value();
                }


                /**
                 * @brief logical default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vlor");

                    return (one.value() || other.value());
                }


                /**
                 * @brief logical default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vland");

                    return (one.value() && other.value());
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "veq");

                    return (one.value() == other.value());
                }


                /**
                 * @brief equatable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vneq");

                    return (one.value() != other.value());
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name conditional modules
         */
        ///@{
        /**
         * @brief conditional
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct zfloat32_conditional
        {
            /**
             * @brief conditional basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief conditional default
                 * @relates float32
                 * @remark scalar default
                 */
                friend zfloat32<Interface::feature_mask> vsel(bfloat32<Interface::feature_mask> condition, Composed if_value, Composed else_value) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vsel");

                    return (condition.value() ? if_value : else_value);
                }

            };

            /**
             * @brief conditional public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::conditional<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name io modules
         */
        ///@{
        /**
         * @brief io
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct bfloat32_io
        {
            /**
             * @brief io basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief io default
                 * @relates float32
                 * @remark scalar default
                 */
                template<typename OutputIt> friend void vstore(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vstore");

                    result[0] = input.value();
                }


                /**
                 * @brief io default
                 * @relates float32
                 * @remark scalar default
                 */
                template<typename OutputIt> friend void vstream(OutputIt result, Composed input) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vstream");

                    result[0] = input.value();
                }


                /**
                 * @brief io default
                 * @relates float32
                 * @remark scalar default
                 */
                template<typename RandomIt> friend bfloat32<Interface::feature_mask> vgather(RandomIt input, const zint32<Interface::feature_mask> &index,  Composed) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vgather");

                    return input[index.value()];
                }

            };

            /**
             * @brief io public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::io<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name bitwise modules
         */
        ///@{
        /**
         * @brief bitwise
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct bfloat32_bitwise
        {
            /**
             * @brief bitwise basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vbneg(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vbneg");

                    auto _one = one.value();
                    float result;
                    bitsof(result) = ~bitsof(_one);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vband(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vband");

                    auto _one = one.value();
                    auto _other = other.value();
                    float result;
                    bitsof(result) = bitsof(_one) & bitsof(_other);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vbor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vbor");

                    auto _one = one.value();
                    auto _other = other.value();
                    float result;
                    bitsof(result) = bitsof(_one) | bitsof(_other);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vbxor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vbxor");

                    auto _one = one.value();
                    auto _other = other.value();
                    float result;
                    bitsof(result) = bitsof(_one) ^ bitsof(_other);
                    return result;
                }


                /**
                 * @brief bitwise default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bool is_set(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "is_set");

                    return one.value() != 0;
                }

            };

            /**
             * @brief bitwise public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::bitwise<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name logical modules
         */
        ///@{
        /**
         * @brief logical
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct bfloat32_logical
        {
            /**
             * @brief logical basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief logical default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vlneg(Composed one) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vlneg");

                    return !one.value();
                }


                /**
                 * @brief logical default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vlor(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vlor");

                    return (one.value() || other.value());
                }


                /**
                 * @brief logical default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vland(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vland");

                    return (one.value() && other.value());
                }

            };

            /**
             * @brief logical public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::logical<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}

        // =================================================================================================================
        /**
         * @name equatable modules
         */
        ///@{
        /**
         * @brief equatable
         * @relates float32
         * @remark scalar
         */
        template<typename Interface, typename Composed>
        struct bfloat32_equatable
        {
            /**
             * @brief equatable basic interface implementation
             * @relates float32
             * @remark scalar
             */
            struct __impl
            {

                /**
                 * @brief equatable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> veq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "veq");

                    return (one.value() == other.value());
                }


                /**
                 * @brief equatable default
                 * @relates float32
                 * @remark scalar default
                 */
                friend bfloat32<Interface::feature_mask> vneq(Composed one, Composed other) 
                {
                    ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "default", "vneq");

                    return (one.value() != other.value());
                }

            };

            /**
             * @brief equatable public interface implementation
             * @relates float32
             * @remark scalar
             */
            template<typename Base>
            using impl = traits::equatable<__impl, Base, Interface, Composed, bfloat32<Interface::feature_mask>>;
        };

        ///@}


        // Type composition ================================================================================================

        /**
         * @name float32 composition
         */
        ///@{

        /**
         * @brief zval composition
         * @relates float32
         * @remark scalar
         * @tparam features feature mask
         */
        template<uint64_t FeatureMask>
        using __zfloat32 = compose_t
        <
            printable<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            convertable<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_io<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_math<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_numeric<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_arithmetic<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_bitwise<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_comparable<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_logical<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_equatable<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl,
            zfloat32_conditional<zval_base<FeatureMask>, zfloat32<FeatureMask>>::template impl
        >;

        /// bfloat32 composition
        /// @tparam features feature mask
        template<uint64_t FeatureMask>
        using __bfloat32 = compose_t
        <
            printable<bval_base<FeatureMask>, bfloat32<FeatureMask>>::template impl,
            convertable<bval_base<FeatureMask>, bfloat32<FeatureMask>>::template impl,
            bfloat32_io<bval_base<FeatureMask>, bfloat32<FeatureMask>>::template impl,
            bfloat32_bitwise<bval_base<FeatureMask>, bfloat32<FeatureMask>>::template impl,
            bfloat32_logical<bval_base<FeatureMask>, bfloat32<FeatureMask>>::template impl,
            bfloat32_equatable<bval_base<FeatureMask>, bfloat32<FeatureMask>>::template impl
        >;

        ///@}
    } // end namespace

    /// public zfloat32 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct zfloat32 :
            public float32_detail::__zfloat32<FeatureMask>,
            public float32_detail::zval_base<FeatureMask>
    {
        /// type tag
        using tag = zval_tag;

        /// complete vector
        using zval_t = zfloat32<FeatureMask>;

        /// complete boolean vector
        using bval_t = bfloat32<FeatureMask>;

        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 1;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = std::array<float, 1>;

        /// scalar type, like int for sse 4x integer vector
        using element_t = float;

        /// mask type for boolean operations
        using mask_vector_t = std::array<bool, 1>;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /**
         * copy constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<std::is_convertible<T, std::array<float, 1>>::value>>// || std::is_convertible<T, float>::value>>
        constexpr zfloat32(const T& other) noexcept
                : float32_detail::zval_base<FeatureMask>(other)
        {}

        /**
         * move constructor
         * @tparam T any type convertable to Vector
         * @param other
         */
        template<typename T, typename = std::enable_if_t<(size > 1) && std::is_convertible<T, std::array<float, 1>>::value>>
        constexpr zfloat32(T&& other) noexcept
            : float32_detail::zval_base<FeatureMask>(std::forward<T>(other))
        {}

        /**
         * copy constructor
         * @param other
         */
        constexpr zfloat32(const bfloat32<FeatureMask>& other) noexcept
            : float32_detail::zval_base<FeatureMask>(other.value())
        {}


        /**
         * @brief constructable 
         * @relates float32
         * @remark scalar 
         */
        constexpr zfloat32(  ) noexcept : float32_detail::zval_base<FeatureMask>()
        {
            ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "", "CONS()");

        }


        /**
         * @brief constructable 
         * @relates float32
         * @remark scalar 
         */
        constexpr zfloat32(float value) noexcept : float32_detail::zval_base<FeatureMask>(value)
        {
            ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "", "CONS(float)");

        }


        /**
         * @brief constructable 
         * @relates float32
         * @remark scalar 
         */
        constexpr zfloat32(extracted_t value) noexcept : float32_detail::zval_base<FeatureMask>(value[0])
        {
            ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "", "CONS(extracted_t)");

        }

    };

    /// public bfloat32 implementation
    /// @tparam FeatureMask feature mask
    template<uint64_t FeatureMask>
    struct bfloat32 :
            public float32_detail::__bfloat32<FeatureMask>,
            public float32_detail::bval_base<FeatureMask>
    {
        /// type tag
        using tag = bval_tag;

        /// complete vector
        using zval_t = zfloat32<FeatureMask>;

        /// complete boolean vector
        using bval_t = bfloat32<FeatureMask>;

        /// vector size (1 - scalar, 4, 8, 16, ...)
        static constexpr size_t size = 1;

        /// memory alignment
        static constexpr size_t alignment = 16;

        /// scalar type? vector type?
        static constexpr bool is_vector = size > 1;

        /// vector type, like __m128i for sse 4x integer vector
        using vector_t = std::array<float, 1>;

        /// scalar type, like int for sse 4x integer vector
        using element_t = bool;

        /// mask type for boolean operations
        using mask_vector_t = std::array<bool, 1>;

        /// extracted std::array of (dim) scalar values
        using extracted_t = std::array<element_t, size>;

        /// Forwarding constructor
        FORWARD2(bfloat32, float32_detail::bval_base<FeatureMask>);


        /**
         * @brief constructable 
         * @relates float32
         * @remark scalar 
         */
        constexpr bfloat32(  ) noexcept : float32_detail::bval_base<FeatureMask>()
        {
            ZTRACE_BACKEND("scalar.float32.impl", __LINE__, "float32(float[1])", "", "CONS()");

        }

    };

    static_assert(is_zval<zfloat32<0>>::value, "is_zval for zfloat32 failed.");
    static_assert(is_bval<bfloat32<0>>::value, "is_bval for bfloat32 failed.");

    static_assert(is_floating_point<zfloat32<0>>::value, "is_floating_point for zfloat32 failed.");
    static_assert(!is_integral<zfloat32<0>>::value, "is_integral for zfloat32 failed.");

    static_assert(is_float<zfloat32<0>>::value, "is_float for zfloat32 failed.");
    static_assert(!is_double<zfloat32<0>>::value, "is_double for zfloat32 failed.");

    ///@}
}}}