//---------------------------------------------------------------------------------
// The MIT License (MIT)
//
// Copyright (c) 2015-2018 Sergej Zuyev (sergej.zuyev - at - zz-systems.net)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//---------------------------------------------------------------------------------

/**
 * @file int8.impl.hpp
 * @brief
 * This file provides defines required components and logic for int8 scalar target.
 * Provides unified access to 1 'int8_t' values
 * @remark
 * This is an autogenerated file. Changes will be lost on regeneration.
 */
#pragma once

#include <type_traits>
#include <cmath>

#include "backend/intrin.hpp"
#include "backend/zval.hpp"

#include "util/type/type_composition.hpp"
#include "util/type/type_traits.hpp"

#include "util/memory.hpp"
#include "util/macros.hpp"

#include "traits/common.hpp"
#include "traits/construction.hpp"
#include "traits/io.hpp"
#include "traits/conditional.hpp"
#include "traits/bitwise_shift.hpp"
#include "traits/logical.hpp"
#include "traits/math.hpp"
#include "traits/arithmetic.hpp"
#include "traits/comparable.hpp"
#include "traits/bitwise.hpp"
#include "traits/equatable.hpp"
#include "traits/numeric.hpp"

namespace zacc { namespace backend { namespace scalar {

    /// @cond
    template<uint64_t features>
    struct bint8;

    template<uint64_t features>
    struct zint8;
    /// @endcond


    // =================================================================================================================
    /**
     * @name construction modules
     */
    ///@{

    /**
     * @brief construction
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_construction
    {

        /**
         * @brief construction basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;


            /**
             * @brief construction 
             * @relates int8
             * @remark scalar 
             */
            constexpr __impl(  ) : Base()  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "", "CONS()");

            }


            /**
             * @brief construction 
             * @relates int8
             * @remark scalar 
             */
            constexpr __impl(int8_t value) : Base(value)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "", "CONS(int8_t)");

            }


            /**
             * @brief construction 
             * @relates int8
             * @remark scalar 
             */
            template <typename T, typename enable = std::enable_if_t<is_zval<T>::value || is_bval<T>::value>> __impl(const T &value) : Base(value.value())  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "", "CONS(const T)");

            }


            /**
             * @brief construction 
             * @relates int8
             * @remark scalar 
             */
            constexpr __impl(std::array<typename Base::element_t, Base::size()> value) : Base(value[0])  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "", "CONS(std::array<typename Base::element_t, Base::size()>)");

            }

        };

        /**
         * @brief construction public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::construction<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name construction modules
     */
    ///@{

    /**
     * @brief construction
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct bint8_construction
    {

        /**
         * @brief construction basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;


            /**
             * @brief construction 
             * @relates int8
             * @remark scalar 
             */
            constexpr __impl(  ) : Base()  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "", "CONS()");

            }


            /**
             * @brief construction 
             * @relates int8
             * @remark scalar 
             */
            constexpr __impl(zval_t value) : Base(value.value() != 0)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "", "CONS(zval_t)");

            }


            /**
             * @brief construction 
             * @relates int8
             * @remark scalar 
             */
            constexpr __impl(bval_t value, last_operation last_op) : Base(value, last_op)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "", "CONS(bval_t value, last_operation)");

            }

        };

        /**
         * @brief construction public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::construction<__impl<base_t>, bint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name io modules
     */
    ///@{

    /**
     * @brief io
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_io
    {

        /**
         * @brief io basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief io default
             * @relates int8
             * @remark scalar default
             */
            template<typename OutputIt> friend void vstore(OutputIt result, Composed input)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vstore");

                result[0] = input.value();
            }


            /**
             * @brief io default
             * @relates int8
             * @remark scalar default
             */
            template<typename OutputIt> friend void vstream(OutputIt result, Composed input)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vstream");

                result[0] = input.value();
            }

        };

        /**
         * @brief io public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::io<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name math modules
     */
    ///@{

    /**
     * @brief math
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_math
    {

        /**
         * @brief math basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief math default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vabs(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vabs");

                return std::abs(one.value());
            }


            /**
             * @brief math default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vmin(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vmin");

                return std::min(one.value(), other.value());
            }


            /**
             * @brief math default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vmax(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vmax");

                return std::max(one.value(), other.value());
            }


            /**
             * @brief math default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vclamp(Composed self, Composed from, Composed to)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vclamp");

                return vmin(to, vmax(from, self));
            }

        };

        /**
         * @brief math public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::math<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name numeric modules
     */
    ///@{

    /**
     * @brief numeric
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_numeric
    {

        /**
         * @brief numeric basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);
        };

        /**
         * @brief numeric public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::numeric<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name arithmetic modules
     */
    ///@{

    /**
     * @brief arithmetic
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_arithmetic
    {

        /**
         * @brief arithmetic basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief arithmetic default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vneg(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vneg");

                return (-one.value());
            }


            /**
             * @brief arithmetic default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vadd(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vadd");

                return (one.value() + other.value());
            }


            /**
             * @brief arithmetic default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vsub(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vsub");

                return (one.value() - other.value());
            }


            /**
             * @brief arithmetic default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vmul(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vmul");

                return (one.value() * other.value());
            }


            /**
             * @brief arithmetic default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vdiv(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vdiv");

                return (one.value() / other.value());
            }


            /**
             * @brief arithmetic default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vmod(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vmod");

                return (one.value() % other.value());
            }

        };

        /**
         * @brief arithmetic public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::arithmetic<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name bitwise modules
     */
    ///@{

    /**
     * @brief bitwise
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_bitwise
    {

        /**
         * @brief bitwise basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vbneg(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbneg");

                return (~one.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vband(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vband");

                return (one.value() & other.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vbor(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbor");

                return (one.value() | other.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vbxor(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbxor");

                return (one.value() ^ other.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend bool is_set(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "is_set");

                return one.value() != 0;
            }

        };

        /**
         * @brief bitwise public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::bitwise<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name bitwise_shift modules
     */
    ///@{

    /**
     * @brief bitwise_shift
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_bitwise_shift
    {

        /**
         * @brief bitwise_shift basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief bitwise_shift default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vbsll(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbsll");

                return (one.value() << other.value());
            }


            /**
             * @brief bitwise_shift default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vbsrl(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbsrl");

                return (one.value() >> other.value());
            }


            /**
             * @brief bitwise_shift default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vbslli(const Composed one, const size_t other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbslli");

                return (one.value() << other);
            }


            /**
             * @brief bitwise_shift default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vbsrli(const Composed one, const size_t other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbsrli");

                return (one.value() >> other);
            }

        };

        /**
         * @brief bitwise_shift public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::bitwise_shift<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name comparable modules
     */
    ///@{

    /**
     * @brief comparable
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_comparable
    {

        /**
         * @brief comparable basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief comparable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vgt(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vgt");

                return (one.value() > other.value());
            }


            /**
             * @brief comparable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vlt(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vlt");

                return (one.value() < other.value());
            }


            /**
             * @brief comparable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vge(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vge");

                return (one.value() >= other.value());
            }


            /**
             * @brief comparable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vle(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vle");

                return (one.value() <= other.value());
            }

        };

        /**
         * @brief comparable public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::comparable<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name logical modules
     */
    ///@{

    /**
     * @brief logical
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_logical
    {

        /**
         * @brief logical basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief logical default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vlneg(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vlneg");

                return (!one.value());
            }


            /**
             * @brief logical default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vlor(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vlor");

                return (one.value() || other.value());
            }


            /**
             * @brief logical default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vland(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vland");

                return (one.value() && other.value());
            }

        };

        /**
         * @brief logical public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::logical<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name equatable modules
     */
    ///@{

    /**
     * @brief equatable
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_equatable
    {

        /**
         * @brief equatable basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief equatable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> veq(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "veq");

                return (one.value() == other.value());
            }


            /**
             * @brief equatable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vneq(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vneq");

                return (one.value() != other.value());
            }

        };

        /**
         * @brief equatable public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::equatable<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name conditional modules
     */
    ///@{

    /**
     * @brief conditional
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct zint8_conditional
    {

        /**
         * @brief conditional basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief conditional default
             * @relates int8
             * @remark scalar default
             */
            friend zint8<Base::features> vsel(bval_t condition, Composed if_value, Composed else_value)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vsel");

                return (condition.value() ? if_value : else_value);
            }

        };

        /**
         * @brief conditional public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::conditional<__impl<base_t>, zint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name io modules
     */
    ///@{

    /**
     * @brief io
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct bint8_io
    {

        /**
         * @brief io basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief io default
             * @relates int8
             * @remark scalar default
             */
            template<typename OutputIt> friend void vstore(OutputIt result, Composed input)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vstore");

                result[0] = input.value();
            }


            /**
             * @brief io default
             * @relates int8
             * @remark scalar default
             */
            template<typename OutputIt> friend void vstream(OutputIt result, Composed input)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vstream");

                result[0] = input.value();
            }

        };

        /**
         * @brief io public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::io<__impl<base_t>, bint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name bitwise modules
     */
    ///@{

    /**
     * @brief bitwise
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct bint8_bitwise
    {

        /**
         * @brief bitwise basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vbneg(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbneg");

                return (~one.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vband(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vband");

                return (one.value() & other.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vbor(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbor");

                return (one.value() | other.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vbxor(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vbxor");

                return (one.value() ^ other.value());
            }


            /**
             * @brief bitwise default
             * @relates int8
             * @remark scalar default
             */
            friend bool is_set(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "is_set");

                return one.value() != 0;
            }

        };

        /**
         * @brief bitwise public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::bitwise<__impl<base_t>, bint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name logical modules
     */
    ///@{

    /**
     * @brief logical
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct bint8_logical
    {

        /**
         * @brief logical basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief logical default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vlneg(Composed one)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vlneg");

                return (!one.value());
            }


            /**
             * @brief logical default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vlor(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vlor");

                return (one.value() || other.value());
            }


            /**
             * @brief logical default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vland(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vland");

                return (one.value() && other.value());
            }

        };

        /**
         * @brief logical public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::logical<__impl<base_t>, bint8<base_t::features>>;

    };

    ///@}


    // =================================================================================================================
    /**
     * @name equatable modules
     */
    ///@{

    /**
     * @brief equatable
     * @relates int8
     * @remark scalar
     */
    template<typename Composed>
    struct bint8_equatable
    {

        /**
         * @brief equatable basic interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename Base>
        struct __impl : Base
        {
            /// complete vector
            using zval_t        = zint8<Base::features>;
            /// complete boolean vector
            using bval_t        = bint8<Base::features>;
            /// type tag
            using tag           = typename Base::tag;

            /// wrapped vector type
            using vector_t      = typename zval_traits<Base>::vector_t;
            /// element type
            using element_t     = typename zval_traits<Base>::element_t;

            /// wrapped mask vector type
            using mask_vector_t = typename zval_traits<Base>::mask_vector_t;

            /// extracted type (for usage in scalar code)
            using extracted_t   = typename zval_traits<Base>::extracted_t;

            /// forward to base
            FORWARD(__impl);

            /**
             * @brief equatable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> veq(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "veq");

                return (one.value() == other.value());
            }


            /**
             * @brief equatable default
             * @relates int8
             * @remark scalar default
             */
            friend bint8<Base::features> vneq(Composed one, Composed other)  {

                ZTRACE_BACKEND("scalar.int8.impl", __LINE__, "int8(int8_t[1])", "default", "vneq");

                return (one.value() != other.value());
            }

        };

        /**
         * @brief equatable public interface implementation
         * @relates int8
         * @remark scalar
         */
        template<typename base_t>
        using impl = traits::equatable<__impl<base_t>, bint8<base_t::features>>;

    };

    ///@}


    // Type composition ================================================================================================

    /**
     * @name int8 composition
     */
    ///@{

        /**
         * @brief zval parametrization using
         * - 'int8_t' as underlying vector type
         * - 'int8_t' as scalar type
         * - '1' as vector size
         * - '16' as alignment
         * @relates int8
         * @remark scalar
         */
        template<uint64_t features>
        struct __zval_int8
        {
            /// vector base
            using zval_base_t = zval<int8_t, bool, int8_t, zval_tag, 1, 16, features>;
            /// boolean vector base
            using bval_base_t = bval<int8_t, bool, 1, 16, features>;

            /// implementation
            struct impl : public zval_base_t
            {
                /// complete vector
                using zval_t = zint8<features>;
                /// complete boolean vector
                using bval_t = bint8<features>;

                /// forward to base
                FORWARD2(impl, zval_base_t);
            };
        };
        /**
         * @brief zval composition
         * @relates int8
         * @remark scalar
         * @tparam features feature mask
         */
        template<uint64_t features>
        struct __zint8
        {
            /// @cond
            struct impl;
            /// @endcond

            /// parametrized zval base
            using zval_t = typename __zval_int8<features>::impl;

            /// compose type from modules
            using composition_t = compose
            <
                printable::impl,
                iteratable::impl,
                convertable::impl,
                zint8_io<impl>::template impl,
                zint8_math<impl>::template impl,
                zint8_numeric<impl>::template impl,
                zint8_arithmetic<impl>::template impl,
                zint8_bitwise<impl>::template impl,
                zint8_bitwise_shift<impl>::template impl,
                zint8_comparable<impl>::template impl,
                zint8_logical<impl>::template impl,
                zint8_equatable<impl>::template impl,
                zint8_conditional<impl>::template impl,
                zint8_construction<impl>::template impl,

                composable<zval_t>::template type
            >;

            /// implementation
            struct impl : public composition_t
            {
                /// complete vector
                using zval_t = zint8<features>;
                /// complete boolean vector
                using bval_t = bint8<features>;

                /// forward to base
                FORWARD2(impl, composition_t);
            };
        };

        /**
         * @brief bval parametrization using
         * - 'int8_t' as underlying vector type
         * - 'int8_t' as scalar type
         * - '1' as vector size
         * - '16' as alignment
         * @relates int8
         * @remark scalar
         * @tparam features feature mask
         */
        template<uint64_t features>
        struct __bval_int8
        {
            /// complete vector base
            using zval_base_t = zval<int8_t, bool, int8_t, zval_tag, 1, 16, features>;
            /// complete boolean vector base
            using bval_base_t = bval<int8_t, bool, 1, 16, features>;

            /// implementation
            struct impl : public bval_base_t
            {
                /// complete vector
                using zval_t = zint8<features>;
                /// complete boolean vector
                using bval_t = bint8<features>;

                /// forward to base
                FORWARD2(impl, bval_base_t);
            };
        };

        /// bint8 composition
        /// @tparam features feature mask
        template<uint64_t features>
        struct __bint8
        {
            /// @cond
            struct impl;
            /// @endcond

            /// parametrized zval base
            using bval_t = typename __bval_int8<features>::impl;
            /// compose type from modules
            using composition_t = compose
            <
                printable::impl,
                iteratable::impl,
                convertable::impl,
                bint8_io<impl>::template impl,
                bint8_bitwise<impl>::template impl,
                bint8_logical<impl>::template impl,
                bint8_equatable<impl>::template impl,
                bint8_construction<impl>::template impl,

                composable<bval_t>::template type
            >;

            /// implementation
            struct impl : public composition_t
            {
                /// complete vector
                using zval_t = zint8<features>;
                /// complete boolean vector
                using bval_t = bint8<features>;

                /// forward to base
                FORWARD2(impl, composition_t);
            };
        };
    //}

    /// public zint8 implementation
    /// @tparam features feature mask
    template<uint64_t features>
    struct zint8 : public __zint8<features>::impl
    {
        /// complete vector
        using zval_t = zint8<features>;
        /// complete boolean vector
        using bval_t = bint8<features>;

        /// forward to base
        FORWARD2(zint8, __zint8<features>::impl);
    };

    /// public bint8 implementation
    /// @tparam features feature mask
    template<uint64_t features>
    struct bint8 : public __bint8<features>::impl
    {
        /// complete vector
        using zval_t = zint8<features>;
        /// complete boolean vector
        using bval_t = bint8<features>;

        /// forward to base
        FORWARD2(bint8, __bint8<features>::impl);
    };

    static_assert(is_zval<zint8<0>>::value, "is_zval for zint8 failed.");
    static_assert(is_bval<bint8<0>>::value, "is_bval for bint8 failed.");

    static_assert(!is_floating_point<zint8<0>>::value, "is_floating_point for zint8 failed.");
    static_assert(is_integral<zint8<0>>::value, "is_integral for zint8 failed.");

    static_assert(!is_float<zint8<0>>::value, "is_float for zint8 failed.");
    static_assert(!is_double<zint8<0>>::value, "is_double for zint8 failed.");

    ///@}
}}}